### ISSUE TITLE
Bubblemap doesnt render correctly when lanched from the wallet.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/explorer-dapp#110]
Render of bubblemap not seen correctly on https://deploy-preview-104--dulcet-cat-1cfbfd.netlify.app/my-wallet

for NFT https://stg.datadex.itheum.io/datanfts/marketplace/DATANFTFT4-3ba099-01a0

Steps to reproduce
1. Browse to wallet
2. Click on "View Data" on the "WEGLD Bubble Map"

The bubblemap launches without any text on the bubbles. The correct view is seen in the App.

![image](https://github.com/Itheum/explorer-dapp/assets/121969933/50cf56a1-2c43-4dd4-b5be-eff99879c1e6)

**Comment by damienen** [comment]
This behavior is intended. Closing.

CC: @newbreedofgeek
