### ISSUE TITLE
Viewing a PDF in wallet is not rendered within the view on #104

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/explorer-dapp#111]
Viewing a PDF from wallet section opens the pdf in a new tab.

The PDF should be rendered within the viewer. Same as in the case of music or JSON and not open in a new tab.

https://devnet-explorer.multiversx.com/nfts/DATANFTFT4-3ba099-01d5

https://deploy-preview-104--dulcet-cat-1cfbfd.netlify.app/my-wallet

Please clarify the expected implementation of this item.

**Comment by newbreedofgeek** [comment]
As per https://github.com/Itheum/explorer-dapp/issues/101

In Wallet VIew, we will only open in a new tab. But show a message to the user that it was opened in a new tab so they are aware this happened.

**Comment by damienen** [comment]
Solved. Closing.
