### ISSUE TITLE
When we "filter" security issues in wallet (for JSON, SVG) - we should inform the user what happened and advice next steps

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/explorer-dapp#119]
This warming message should ONLY appear in :
- Wallet View on Explorer
- For SVG, JSON and HTML files (NOT for PDFs, Images, MP3)

Like this:
<img width="1161" alt="image" src="https://github.com/Itheum/explorer-dapp/assets/743169/c06fb18e-b5d5-43f1-8468-d23d7e9dad6f">

<img width="1188" alt="image" src="https://github.com/Itheum/explorer-dapp/assets/743169/706bd6d9-d2d0-4dfa-b794-f0619e602afc">

**Comment by vmradulescu** [comment]
Tested on xportal, defi wallet and web wallet.

Warning appears only for JSON,SVG and HTML files.

However, there is an issue where the warning message is visible on the signing message pop-up, when you follow these easy to repro steps (xportal):

- view data on one of the compatible formats
- when the sign message pop-up appears, close it, but accept the message on xportal. Notice nothing will happen
- press view data again
- Notice the message is present in the sign message pop-up

![image](https://github.com/Itheum/explorer-dapp/assets/141028717/821d44cc-be72-4ff2-bb0b-0eba2fa91153)

**Comment by vmradulescu** [comment]
Verified.
