### ISSUE TITLE
For MultiversX Bubbles - allows the user to Open the SVG in a new tab

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/explorer-dapp#120]
So user can open the SVG in their browser's default full screen mode, we give them this option as well.

Like This:
<img width="1358" alt="image" src="https://github.com/Itheum/explorer-dapp/assets/743169/5183e120-7b63-46c0-a5b1-e14c1608988c">

**Comment by damienen** [comment]
Solved. Closing.
