### ISSUE TITLE
Explorer: Automatic NativeAuth Login should be supported in same specs as xPortal Hub

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/explorer-dapp#128]
The Data DEX supports NativeAuth via the xPortal Hub app. We made this change in the Data DEX code. I believe it reads a "url parameter" that xPortal Hub injects and we then automatically login the user via Dapp Core.

We need to do this exact same with Explorer DApp. This will allow for a Data DEX logged in user to click on "Explore" and come direct to the Explorer app to open their Data NFTs without having to re-login

**Requirements:**
- Support NativeAuth login in same specification as xPortal Hub
- Automatic Login should happen on same link user arrives on. e.g. if user comes here `https://explorer.itheum.io/multiversx-infographics` with the accessToken, then Explorer needs to login user on this same URL and keep the user here. (no redirects to another URL)

**Comment by damienen** [comment]
The "Support NativeAuth login in same specification as xPortal Hub" is already met because we use sdk-dapp

**Comment by damienen** [comment]
The second pecification is already present in the other ticket:

https://github.com/Itheum/data-dex/issues/1008

The first one is already met so this is should be closed without resolution as no extra code is added for it work.
