### ISSUE TITLE
Explorer Trailblazer App View Re-design

### ISSUE THREAD

**Issue by vmradulescu** [Itheum/explorer-dapp#131]
Expectation:

Explorer Trailblazer App needs to be redesinged based on the following parameters:

- When in view data mode, the window with the timeline elements of the trailblazer is currently showing each entry. This means, that in time, the timeline will be long, the user needing to do a lot of scrolling if he wants to view older data. 

In the new design, each category of item in the timeline will only be displayed once.

This means that the timeline will only display 1 entry per each category. Quests, Quizz, Leaderboard, Shopify, Article or other.

![1](https://github.com/Itheum/explorer-dapp/assets/141028717/2f7de4cf-c1d1-4378-a39e-b8448ab29c26)

Additionally, in order to view older data entries for each category there will be a button to press on each timeline element which will open a separate window where all the other entries in that category will be displayed. They will be displayed from newest to oldest, with the possibility to click on them to be redirected to the appropriate link.

![2](https://github.com/Itheum/explorer-dapp/assets/141028717/d25d90fd-4473-453e-a4ce-d863b0728757)

Product Spec creation: 24th of August
Brief and assignment: 
Development: 
Final testing: 
Deployment: Version 1.5 of the explorer

*Timeline may change

**Comment by newbreedofgeek** [comment]
Should be tested by buying this one on devnet : https://stg.datadex.itheum.io/datanfts/marketplace/DATANFTFT4-3ba099-01a7

**Comment by vmradulescu** [comment]
@newbreedofgeek I would propose two solutions at this point:

- Easy solution: Separate tab view, but that would break the imersion from the app and be disruptive
- Complex solution: Slide out to the right, keeping the same visuals, just changing the data displayed. That way, we do not break immersion and also, it doesn't look weird when we are interacting with google other pop-ups such as google forms.

**Comment by newbreedofgeek** [comment]
Related to https://github.com/Itheum/explorer-dapp/issues/68

**Comment by damienen** [comment]
Currently categories are not grouped when looking at the whole timeline, but considering the way it works I will close this as I believe the user experience is better like this. You can see the whole timeline and if you want to see specifics you can categorize them and see only what you need.

Works. Closing!
