### ISSUE TITLE
Models not styled for Dark Mode

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/explorer-dapp#133]
Following models are not styled for Dark Mode

- My Wallet View Data Model
<img width="1025" alt="image" src="https://github.com/Itheum/explorer-dapp/assets/743169/71bf25f3-c08c-4d5c-be7b-8f173fdae178">

- ALL Apps in the Marketplace

<img width="1030" alt="image" src="https://github.com/Itheum/explorer-dapp/assets/743169/47967a37-9bf2-4ee9-b00d-5dbca9c91ecc">

- XPortal Login Model
<img width="1079" alt="image" src="https://github.com/Itheum/explorer-dapp/assets/743169/89c92aaf-435e-46ab-bae4-c36abfea2955">

- Ledger Login Model
<img width="1076" alt="image" src="https://github.com/Itheum/explorer-dapp/assets/743169/68989864-361b-40e9-b92f-e2a4cacf3758">

**Comment by vmradulescu** [comment]
Fix verified.
