### ISSUE TITLE
HOTFIX : When you toggle Dark Mode -- the button loses position when you reload

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/explorer-dapp#134]
1. By default we are on light mode. Toggle Button looks like this
<img width="537" alt="image" src="https://github.com/Itheum/explorer-dapp/assets/743169/6f24d0e4-46f3-4f92-b498-11df69c04126">

2. I move it to Dark mode and the button looks like this (this is correct)
<img width="540" alt="image" src="https://github.com/Itheum/explorer-dapp/assets/743169/e67baac9-7f49-47e1-95b5-3450c72d54f2">

3. I'm in dark mode now... I now reload the page. Background is dark but the toggle button is in "reset" and you need to toggle 2 times to get to light mode again
<img width="539" alt="image" src="https://github.com/Itheum/explorer-dapp/assets/743169/9d5e1c0b-c984-4501-8b2d-ac8b04c57d10">

--- 

3) is an issue... when you reload the page the toggle button should stay on dark or light setting

**Comment by newbreedofgeek** [comment]
The text is now working to be dark vs light mode..

BUT the model BG is still white. It needs to be all dark mode. Live on the live explorer.itheum.io

**Comment by damienen** [comment]
Solved. Closing.
