### ISSUE TITLE
Frontend integration of Trending + Recent Data NFTs (explorer)

### ISSUE THREAD

**Issue by damienen** [Itheum/explorer-dapp#139]
A/C:

- Show 10 Trending Data NFTs on Home page under the Data Widgets (User can be Logged In or NOT logged In)
- Show 10 Recent  Data NFTs on Home page under the Data Widgets (User can be Logged In or NOT logged In)
- When each item tile is clicked, on a new window, take them to the "deep link". e.g. https://datadex.itheum.io/datanfts/marketplace/DATANFTFT-e936d4-04/offer-226
- The Data NFT tiles does NOT need the HEART favorite icon but he rest looks exactly the same as Data DEX
- With this feature, you will be using the web2 API... And you need to do "defensive coding", where if the Web2 API is down or broken etc... the Trending and Recent UI blocks just hide and there are no runtime error that stop the user from using other Explorer features

**Comment by fuzzyduke** [comment]
Requirements have been met.
1. Trending and recent Data NFTs show similar to the Datadex.
2. Clicking on any item takes us to the datadex to the relevant Item.
3. Favorites/Heart icon is not seen on the explorer.
