### ISSUE TITLE
View Data needs to support Web Wallet

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/explorer-dapp#15]
You can't view data with Web Wallet.

MX team has told us that signatures via MX template should work.

- When user clicks on "view data" from any screen (wallet, listed, or app view)
- User is on Web Wallet, the data marshal signature should be redirected to web wallet and sent back to our explorer and the data should unlock

**Comment by icegriffinguru** [comment]
Fixed

**Comment by damienen** [comment]
Solved. Closing.
