### ISSUE TITLE
Session Expiration Warning screen is not optimized for Dark Mode

### ISSUE THREAD

**Issue by vmradulescu** [Itheum/explorer-dapp#158]
While using native auth, in dark mode, on explorer, when the session expiration warning screen pop-up appears, it is not optimized for dark mode. It still uses the color scheme optimized for the light mode.

![image_480](https://github.com/Itheum/explorer-dapp/assets/141028717/ce95f476-673c-4493-ac4e-9b897ef0dbb9)

**Comment by damienen** [comment]
Solved. Closing.

**Comment by vmradulescu** [comment]
![Image](https://github.com/Itheum/explorer-dapp/assets/141028717/f00f4300-f2e4-4af6-af83-7db7bc9e6eea)


Still dont fully like it honestly. Its ok, but it could be better.
