### ISSUE TITLE
When user clicks on "Identifier", we should open the Data NFT in the marketplace details view

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/explorer-dapp#16]
- In ALL the sections (wallet, listed, apps etc) that show these Data NFT "tiles", we show 'identifier'. In this example, the identifier is `DATANFTFT4-3ba099-01a7`
<img width="373" alt="image" src="https://github.com/Itheum/explorer-dapp/assets/743169/4ebaa5a1-1187-47a1-90ad-29827e987a75">

- This needs to be made into a "link" that looks similar to this:
<img width="151" alt="image" src="https://github.com/Itheum/explorer-dapp/assets/743169/f5045568-a8cd-49b9-839e-72e7bee00981">

but with this icon 
<img width="23" alt="image" src="https://github.com/Itheum/explorer-dapp/assets/743169/5d8cadf3-6e34-4d5f-975d-8a82fa317f0c">

- When the user clicks on this it needs to go in the data nft marketplace details page in a seperate window. e.g.
https://stg.datadex.itheum.io/datanfts/marketplace/DATANFTFT4-3ba099-01a7

- based on if it's mainnet or devnet it should be stg.datadex.itheum.io or datadex.itheum.io

**Comment by icegriffinguru** [comment]
Fixed

**Comment by fuzzyduke** [comment]
Is updated in App sections and my wallet.
Clarification: should this be updated for "Offering" in "My listed" sections?

![image](https://github.com/Itheum/explorer-dapp/assets/121969933/f3ebc030-8310-47c2-855f-9bd63b3b2161)

**Comment by damienen** [comment]
Should show identifier instead of offering, too. Easy fix, though

**Comment by fuzzyduke** [comment]
Verified fixed on #721

![image](https://github.com/Itheum/explorer-dapp/assets/121969933/989be5d4-3332-4cfd-bd9a-b77c7efc019b)
