### ISSUE TITLE
Misc Bugs to be fixed

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/explorer-dapp#17]
- [x] Royalties issue
<img width="304" alt="image" src="https://github.com/Itheum/explorer-dapp/assets/743169/37926381-3cf6-4ea3-94c7-f8648fde37a1">

- [x] When user is NOT logged in, it should show the below changes.
<img width="774" alt="image" src="https://github.com/Itheum/explorer-dapp/assets/743169/0d9044ee-dafc-41c6-a924-8387f0df57f5">

**Comment by icegriffinguru** [comment]
Fixed

**Comment by fuzzyduke** [comment]
Please align buttons when user is logged in. 
![image](https://github.com/Itheum/explorer-dapp/assets/121969933/be95f956-6d04-4aba-8884-fcd01c1ef42f)

**Comment by icegriffinguru** [comment]
Fixed, @fuzzyduke

**Comment by icegriffinguru** [comment]
Fixed
