### ISSUE TITLE
Odd overlay seen when redirecting Attempting to launch TB.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/explorer-dapp#176]
Odd overlay seen when redirecting Attempting to launch TB.

https://test.explorer.itheum.io/project-trailblazer

![image](https://github.com/Itheum/data-dex/assets/121969933/31a1654e-22fc-411c-836e-baf31d3c903f)

**Comment by damienen** [comment]
Can't reproduce. Please reopen with some instructions to reproduce. A video would be best
