### ISSUE TITLE
Native Auth Cross Dapp session: Logging out of explorer does not invoke a log out action. This is noticed when logging in from datadex and being redirected to explorer.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/explorer-dapp#177]
Logging out of explorer does not invoke a log out action. This is noticed when logging in from datadex and being redirected to explorer. (Not being logged into the explorer previously - native auth testing)

Its seems to work fine if the user logs in from the explorer itself.

wallet: Web wallet

Native Auth cross dapp testing steps.
1. Make sure you are logged out of both Datadex and explorer
2. Log into datadex with web wallet
3. Click explore on a TB
4. You will be logged into the Explorer automatically with the accesss token.
5. Attempt logging out.
6. No action is seen.

**Comment by fuzzyduke** [comment]
Same behavior is seen when logging into the explorer first.

**Comment by damienen** [comment]
This can be added later. We can ask MultiversX to make the functionality work

**Comment by damienen** [comment]
Let's keep track of this issue:
https://github.com/multiversx/mx-sdk-dapp/issues/935

**Comment by CiprianDraghici** [comment]
Please check my anwser here:
https://github.com/multiversx/mx-sdk-dapp/issues/935#issuecomment-1733840375

**Comment by damienen** [comment]
Solved thanks to @CiprianDraghici . Closing
