### ISSUE TITLE
On the Music App if there are 4 songs in the playlist, we see the count but not all 4, you need to click on the list icon.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/explorer-dapp#178]

**Comment by fuzzyduke** [comment]
On the Music App if there are 4 songs in the playlist, we see the count but not all 4, you need to click on the list icon.

![Image](https://github.com/Itheum/explorer-dapp/assets/121969933/feb59186-dd2a-4249-b153-cd560e468dd5)

![Image](https://github.com/Itheum/explorer-dapp/assets/121969933/013ec87a-9b2a-41cb-ba7e-b2ed4192e193)

**Comment by vmradulescu** [comment]
Fixed on latest PR: https://deploy-preview-190--dulcet-cat-1cfbfd.netlify.app/nftunes

You can now use arrows to scroll through the list. Maximum displayed is 4.
