### ISSUE TITLE
if there are 2 songs or more in a playlist then upon completion of the first song there has to be an option to autoplay the next song.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/explorer-dapp#179]
If there are 2 songs or more in a playlist then upon completion of the first song there has to be an option to autoplay the next song. 

Currently if the first song is over you have to select and play the second song or click on next song.

**Comment by damienen** [comment]
This can be an improvement in the next version, moving to 1.8.0

**Comment by fuzzyduke** [comment]
Verified. Passed.
