### ISSUE TITLE
Upon selecting list view, we see a list of the songs however there is no back button, the only way to see the player again is to click on a song.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/explorer-dapp#180]
Upon selecting list view, we see a list of the songs however there is no back button, the only way to see the player again is to click on a song.

![Image](https://github.com/Itheum/explorer-dapp/assets/121969933/a9985c09-36f7-49d6-aafd-6faa6e0b532f)

**Comment by vmradulescu** [comment]
Fixed on latest PR: https://deploy-preview-190--dulcet-cat-1cfbfd.netlify.app/nftunes
