### ISSUE TITLE
Eror seen while launching Data NFT in NF-Tunes - not reproduceable.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/explorer-dapp#181]
The Same Data NFT was working a few minutes prior. However on launching from the app again the below was seen.

![Image](https://github.com/Itheum/explorer-dapp/assets/121969933/7694fbb0-7b94-42a3-9a8a-dd9676686ef1)

**Comment by newbreedofgeek** [comment]
This is that weird error we are seeing sometimes on productions as well..

i.e. 
`MA-7-2 native auth token unpacking threw as error`

We should try and find steps to reproduce it... until then we can proceed with the release i feel as it's not reproducable

**Comment by newbreedofgeek** [comment]
closing until we can reproduce it
