### ISSUE TITLE
[NF-Tunes] Song Cover link is not hidden, user can view the real data source

### ISSUE THREAD

**Issue by vmradulescu** [Itheum/explorer-dapp#183]
[NF-Tunes] Song Cover link is not hidden, user can view the real data source

Steps to repro:

Go to the NF-Tunes App
View Data on any applicable NFT in the list
Right click any of the cover photo and open in new tab to view the link
Alternatively, press F12, go to sources and expand dataassetsdevnet.ygfpmusic.com
Notice that the cover links are not encrypted/hidden and that the user is aware of the direct bucket link

![image](https://github.com/Itheum/explorer-dapp/assets/141028717/c5c3c26d-f25c-41a7-a2a0-0b8f9ec0ad3a)

![image](https://github.com/Itheum/explorer-dapp/assets/141028717/df310eff-8ab1-4a49-9bf0-67261fb594ae)

Expected result: The album cover or any other data that is pulled from the bucket is hidden/encrypted.

Please note that this issue is not happening when playing the music, as is evident from the URL in the network tab.
![image](https://github.com/Itheum/explorer-dapp/assets/141028717/1f8c5f24-8863-49a7-9c83-a42c897af07f)

**Comment by damienen** [comment]
As long as the song is not viewable that is fine.
