### ISSUE TITLE
Login using the xportal is not working

### ISSUE THREAD

**Issue by vmradulescu** [Itheum/explorer-dapp#186]
Login using the xportal is not working

Steps to repro:

Open the https://test.explorer.itheum.io/ and try to login via xportal (tried on chrome,firefox,edge, android mobile)
Notice that it takes a long time for the QR code to be displayed (15 seconds or so)
When opening the xportal it says the qr code is invalid

Below the error in the console, hope it helps

![image](https://github.com/Itheum/explorer-dapp/assets/141028717/c8a6bd94-2df0-472d-8a9d-7ee6e9544171)

**Comment by damienen** [comment]
Solved. Closing
