### ISSUE TITLE
NF-Tunes App does not render Music Data NFT.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/explorer-dapp#204]
NF-Tunes App does not render Music Data NFT. The below error is seen while launching the data NFT via the APP.

![image](https://github.com/Itheum/explorer-dapp/assets/121969933/67afae5f-a41a-4426-abc6-c9109dc366de)

**Comment by fuzzyduke** [comment]
This seems to be the case for the Bubbles app as well.

TB app and esdt app show the below error.

![image](https://github.com/Itheum/explorer-dapp/assets/121969933/fa7f72e5-e238-4858-9a14-53cf04fda0fb)

**Comment by fuzzyduke** [comment]
Assumption, this is a caching issue seems fine on another browser with cache and cookies.

**Comment by fuzzyduke** [comment]
For the first issues, Tried manually logging out and back in and did not notice the same error. 

This may indicate that manual logout is performing some action that clears the token? However, if a User doesn't manually logout but logs in after a few days then they may see the error.

**Comment by damienen** [comment]
Duplicate. Closing
