### ISSUE TITLE
NFTune Issue where the app slides out of view

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/explorer-dapp#206]
Have a look a this video:
https://www.loom.com/share/2860e3d0b1b8402492986ecb327d2661

- Manu's data nft app slides out of view for some reason... but I can hear the music. This does not happen with the older test music data nft
- This may be relalted to the fact that previously I played around with manu's data nft by clicking on next/back, switch to list view etc

**Comment by newbreedofgeek** [comment]
Seems to be related to screen size... and the fact that manu has more tracks

When i go to a super large screen it works... but on my laptop it does now.

**Comment by damienen** [comment]
Checked. It is solved. Closing
