### ISSUE TITLE
Launch app buttons are not working when on the specific "dashboard" home page of explorer

### ISSUE THREAD

**Issue by vmradulescu** [Itheum/explorer-dapp#209]
Launch app buttons are not working when on the specific "dashboard" home page of explorer

Steps to repro:

Login to the https://stg.explorer.itheum.io
Make sure you are on the /dashboard link https://stg.explorer.itheum.io/dashboard
In order to make sure this, press the home button on the top right
Hover any of the apps, and *very important* wait for the animation to finish. 
Notice that if you click the "launch app" button, nothing happens

This issue only occurs on the dashboard.

https://www.loom.com/share/b9670677008541f385bf6b4e3df236a3

**Comment by damienen** [comment]
Closing.
