### ISSUE TITLE
Previous song continues is still loaded when switching to a song that cannot load

### ISSUE THREAD

**Issue by vmradulescu** [Itheum/explorer-dapp#210]
Previous song continues is still loaded when switching to a song that cannot load

Steps to repro:

Login to https://deploy-preview-203--dulcet-cat-1cfbfd.netlify.app/nftunes
Make sure you have a copy of the "First MusicX Album" that was specifically created with the 2n song not being able to load
https://test.datadex.itheum.io/datanfts/marketplace/DATANFTFT4-3ba099-0211

Go to NF Tunes app and view data for the above Data NFT
Load the first song and press play
Load the second song. You will be presented with an error message and the play button will be replaced with a spinning icon for loading, but the file will not load
Move the song progress bar to any position. Notice that the spinning icon has been replaced with the play button
Hit play and notice that the first song that was loaded is now playing, but the artwork and title is displayed for the second song

Expected result: You are unable to play when selected a song that cannot load.

https://www.loom.com/share/5479864776394447a538eedb71e0de48

**Comment by 911-Benedek-RobertGeorge** [comment]
solved

**Comment by damienen** [comment]
Checked. It is good. Closing
