### ISSUE TITLE
Over lap seen in description of Data NFT when text is more.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/explorer-dapp#226]
When there is excess text for the space then we should have the option to "see more". There should be no overlap.

![image](https://github.com/Itheum/explorer-dapp/assets/121969933/c790cfb3-bf2d-433d-98a1-961f4c0cf04d)

**Comment by damienen** [comment]
Add a show more button

**Comment by fuzzyduke** [comment]
Truncated text observed on Android. 

![image](https://github.com/Itheum/explorer-dapp/assets/121969933/b942ba43-78a9-429b-9575-5af3f420ac28)

**Comment by fuzzyduke** [comment]
Scroll is now observed to see all text in description.

Note: scroll becomes visible upon interaction with the block.
