### ISSUE TITLE
My Listing: Single card has empty fields

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/explorer-dapp#23]
Image and card fields does not populate for a single card.

In the same page we see the same Data NFT with another offer with all fields populated.

Step to reproduce is not clear.

https://stg.datadex.itheum.io/datanfts/marketplace/DATANFTFT4-3ba099-01a7
![image](https://github.com/Itheum/explorer-dapp/assets/121969933/caef589d-0fe8-4162-a068-02406d28ebbf)
![image](https://github.com/Itheum/explorer-dapp/assets/121969933/a6109adb-b01f-43db-bbab-fb7d3a36525d)

**Comment by damienen** [comment]
Can't reproduce
