### ISSUE TITLE
File is not viewable on stg.explorer when coming from stg.datadex when connected with xportal hub.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/explorer-dapp#238]
Xportal hub extension testing

Observed on stg.explorer when coming from stg.datadex. However after clearing cache it was fine.

![image](https://github.com/Itheum/explorer-dapp/assets/121969933/8b8fdddb-9c48-4088-a38b-abeb72ede898)

**Comment by damienen** [comment]
If it was ok after cache clear it's ok. Closing for now. Reopen if you find more stuff
