### ISSUE TITLE
"Explorer Apps" need to be renamed to "Itheum Data Widgets".

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/explorer-dapp#240]
As part of a product rebrand, "Explorer Apps" have been renamed to "Itheum Data Widgets"... this is due to confusion on what an itheum app is.. for e.g. if someone builds a 3rd party app using itheum and it runs somewhere else, that can be a Itheum Data.

The UIs should change to reflect this.

**Comment by damienen** [comment]
Solved. Closing.
