### ISSUE TITLE
Music playlist data NFT minted via zstorage Does no play on NF-Tunes

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/explorer-dapp#242]
Music playlist data NFT minted via zstorage Does no play on NF-Tunes

Empty page seen when playing music data NFT with source of playlist generated from NF-Tunes.

![Image](https://github.com/Itheum/explorer-dapp/assets/121969933/14488423-cdaa-4c20-a585-6ad029a53196)

Data NFT to test
https://test.datadex.itheum.io/datanfts/marketplace/DATANFTFT-e0b917-0a/offer-12

**Comment by 911-Benedek-RobertGeorge** [comment]
the files needs to be pinned and it takes a while, now it works, at least for the images, even tho it passed like 7 hours the songs are not playing. 
Also I guess this error should be solved for nf-tunes to throw an allert in app .

**Comment by 911-Benedek-RobertGeorge** [comment]
Another problem is that im able to see the "file" link of the music if im opening it from wallet 

![Image](https://github.com/Itheum/explorer-dapp/assets/72063093/b37b2fca-2982-4ee0-b137-59a5d0d3b244)

**Comment by damienen** [comment]
Solved. Closing.
