### ISSUE TITLE
Get rid of Bootstrap in explorer

### ISSUE THREAD

**Issue by Enciusan** [Itheum/explorer-dapp#244]

**Comment by damienen** [comment]
Your build failed. You need to remove all bootstrap references

**Comment by damienen** [comment]
Some bugs I found while looking around:

- [ ] Error popups do not fit the whole message if it is too big
![Image](https://github.com/Itheum/explorer-dapp/assets/44813558/ded974b7-b896-4b29-b4d3-2fabbb41bcdf)

- [ ] X button looks weird when focused in File Viewer
![Image](https://github.com/Itheum/explorer-dapp/assets/44813558/b5a04b92-5c2c-449a-a199-01129c8a33e1)

- [ ] Play icon is not centered on button on NF-Tunes
![Image](https://github.com/Itheum/explorer-dapp/assets/44813558/23897e0e-d4cf-47bc-bf35-a3a1d0daeb75)

- [ ] Can't press Trailblazer items in the trailblazer widget

- [ ] View in full screen button is not long enough in PDF widget
![Image](https://github.com/Itheum/explorer-dapp/assets/44813558/56a4e64c-5126-4939-ac31-d31168a23d16)

- [ ] The button to open a PDF is not long enough after viewing data of a PDF in wallet
![Image](https://github.com/Itheum/explorer-dapp/assets/44813558/23828bef-714a-453e-8c5c-f65ec3dfe4d0)

**Comment by newbreedofgeek** [comment]
On Laptop screen, the app tiles are too big. Ideally we need 3 in a row and then wrap to next line. Maybe we can make the whole app tile smaller.

<img width="1221" alt="image" src="https://github.com/Itheum/explorer-dapp/assets/743169/57cd271f-c039-439c-841c-a9fda48787ae">

**Comment by damienen** [comment]
Solved. Closing.
