### ISSUE TITLE
NFTunes New Landing page for CoinTelegraph Ad Campaign

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/explorer-dapp#266]
CoinTelegraph will launch a Ad campaign that directly goes to this page:

https://explorer.itheum.io/nftunes

A new updated landing page will be put in place to capture more attention. Design will come from Designer shortly.

**Comment by newbreedofgeek** [comment]
@fuzzyduke pls test this new landing page. It should provide all the functionally of the previous NF.Tunes app (open and listen to music in a player)

**Comment by fuzzyduke** [comment]
Functionality works fine @newbreedofgeek @911-Benedek-RobertGeorge 

1. Preview songs works.
2. Main music data NFT works with the player functions; next song, list view, replay.
3. If user does not hold the data NFT, they are able to see "view in marketplace" which redirects them to the data NFT detail page, where they have to log in again to buy the data NFT.
4. Similar behavior seen for additional music data NFTs.

Some observations:

1. Noticed the bug where users have to attempt multiple login as the first one fails.(Known bug)
2. Text alignment on this section.

![Image](https://github.com/Itheum/explorer-dapp/assets/121969933/420cb6e5-8fe6-425f-b996-d5651c9b46d6)

**Comment by fuzzyduke** [comment]
Also If the user is playing the preview song of the main data NFT and clicks on list they see the below, and it does not close.


![Image](https://github.com/Itheum/explorer-dapp/assets/121969933/28fe4af1-20c2-4db6-8b1b-5ead891c6671)

**Comment by fuzzyduke** [comment]
As a suggestion the numbers can be top-left aligned.

![Image](https://github.com/Itheum/explorer-dapp/assets/121969933/72d2febd-0167-4c27-9c49-2af211eb69d8)

If possible can the 'x' be placed on the right side, currently it doesnt give the notion it is clickable.

![Image](https://github.com/Itheum/explorer-dapp/assets/121969933/a0d8e115-6bf7-4267-b264-a7d830c8c6bf)

**Comment by fuzzyduke** [comment]
Verified fixed.
1. Text is properly aligned.
![Image](https://github.com/Itheum/explorer-dapp/assets/121969933/de6ec8b5-7e84-46cb-b11b-9e5d76234736)

2. For the time being the 'x' will be as it is, in future releases better UI for the toasts need to be revisited.
