### ISSUE TITLE
Fix Theming Issues

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/explorer-dapp#27]
- [ ] Wallet Popups need to be themed in Dark mode. e.g. 
1. xPortal Login Popups and TX Signing Popups
<img width="800" alt="image" src="https://github.com/Itheum/explorer-dapp/assets/743169/f1e91165-18d2-4310-82a8-8264bcfb631b">

2. Ledger Login Popups and TX Signing Popups
<img width="867" alt="image" src="https://github.com/Itheum/explorer-dapp/assets/743169/cd24aa68-b27a-4331-be3f-5880a9278fe7">

**Comment by icegriffinguru** [comment]
Fixed

**Comment by damienen** [comment]
Solved. Closing.
