### ISSUE TITLE
Itheum Explorer round royalties not done correctly

### ISSUE THREAD

**Issue by damienen** [Itheum/explorer-dapp#275]
![Image](https://github.com/Itheum/explorer-dapp/assets/44813558/a018fd4e-373d-4af4-aa31-16781351bd61)

This should be 3.22, not 3.21

**Comment by Enciusan** [comment]
On mainnet TB the royalties on explorer should be 3.22%, i've fixed the problem when show 3.21%

**Comment by damienen** [comment]
Checked by switching to mainnet locally on @Enciusan 's branch. Works. Closing.
