### ISSUE TITLE
In Light Mode: Features Artist Box is not readable

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/explorer-dapp#280]
All Text / headings cannot be read in Light mode. Needs to be fixed.

<img width="884" alt="image" src="https://github.com/Itheum/explorer-dapp/assets/743169/c18aa0e0-6103-455b-827c-1805fb9a9fd8">

**Comment by fuzzyduke** [comment]
This section needs to be visited as well

![image](https://github.com/Itheum/explorer-dapp/assets/121969933/f50b8138-f2c3-4ef9-8246-b8fdcf254452)

**Comment by fuzzyduke** [comment]
@harbzy kindly review light mode.

**Comment by fuzzyduke** [comment]
Light mode iterated for block. Closing

![Image](https://github.com/Itheum/explorer-dapp/assets/121969933/1ebc3087-147f-4fec-9634-0ef0e6f16aa9)
