### ISSUE TITLE
Benchmark NFTunes view data

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/explorer-dapp#281]
1. Clicked on View Data in the Featured artist Section. and Nothing happens.

<img width="888" alt="image" src="https://github.com/Itheum/explorer-dapp/assets/743169/f1f1339b-eee6-40eb-916c-19f4c330a73e">

<img width="1261" alt="image" src="https://github.com/Itheum/explorer-dapp/assets/743169/5382854c-b206-4cc5-a268-cc382a33489a">

**Comment by newbreedofgeek** [comment]
@911-Benedek-RobertGeorge also please make sure the correct Manu Data NFT is shown in Mainnet vs Devnet.

CC @fuzzyduke

**Comment by fuzzyduke** [comment]
Need to investigate the loading time @911-Benedek-RobertGeorge

**Comment by fuzzyduke** [comment]
Seems to take time in the "My Wallet" page as well.

**Comment by fuzzyduke** [comment]
Moving to 1.12 as marshal review is required. 5-6 seconds is the current benchmark that has to be optimized.

**Comment by 911-Benedek-RobertGeorge** [comment]
Location- Romania, Bihor 
Platform- Chrome 
Wallet- DeFi erd1vyejv52e43fxq96cschyyj9g57qn9kgtxrhkg92eyhfu5a022plqtdxvdm
Speed Test- https://www.speedtest.net/result/15984530570
Time in seconds until music started : 
1: 10.22
2: 13.36
3: 09,81
4:  08:95
after a 30-60 min break and re-login
5: 11:23 , + ~9:50 for the big song
6: 12:68

On brave : 
1: 09:80
2: 10:18
Firefox
1: 10:45 

An average of 10 secs 

Improvements : maybe trying to only fetch the first song initially and only then put in queue the rest of the songs

**Comment by fuzzyduke** [comment]
Windows 10
Chrome: Version 122.0.6261.112 (Official Build) (64-bit)
Wallet: erd1xdq4d7uewptx9j9k23aufraklda9leumqc7eu3uezt2kf4fqxz2sex2rxl

**Datadex**
first click	        	11 seconds
click 	        	8  seconds
click 	        	8  seconds
click		        	8.5 seconds
refresh and click	8  seconds

**Explorer**
first click	        	11 seconds
click 		   	10 seconds
refresh and click	12 seconds
click		        	12 seconds
click		        	11 seconds

For Explorer it is noticed that after clicking view data, on the 5th second the player loads up, and then the actual song loads up on the seconds mentioned above.

**Comment by damienen** [comment]
Windows 11
Chrome 122.0.6261.112
Cluj, Romania
Wallet: Extension
Speed: https://www.speedtest.net/result/15995915547
Network: MvX mainnet
NFT: DATANFTFT-e936d4-04

Data Dex:
1. ~8.5 sec
2. ~8.1 sec
3. ~8.3 sec (deleted cache)
4. ~8.7 sec
5. ~7.9 sec

Explorer:
1. ~11.4 sec (deleted cache)
2. ~9.8 sec
3. ~9.5 sec
4. ~10.1 sec
5. ~11.0 sec

**Comment by bucurdavid** [comment]
MacOs Sonoma 14.4 (23E214)
Version 122.0.6261.112 (Official Build) (arm64)
Cluj Romania
Wallet extension
Speed: https://www.speedtest.net/result/15996495837

Explorer: 
1. 10,98 sec 
2. 11,08 sec
3. 10,36 sec 
4. 11,16 sec
5. 9,93 sec

<img width="879" alt="image" src="https://github.com/Itheum/explorer-dapp/assets/46384319/248dd79f-f33c-4ce0-a4fd-7e5b7e4ac637">

In the image above first request is a request with stream in line, most probably the manifest file. As seen in the image, the second request is for the first song (id 1) and is after the first request finality (3.45 sec). 

FE Improvement: don't wait for the first request to finish, request the song with id 1, as it always will be available. 
should result in  ~5-6 seconds loading time until sound is heard.

BE improvement: find ways to lower the 5-6 seconds response time.

**Comment by Enciusan** [comment]
Operation system: MacOS sonoma 14.4
Location: Bucharest Romania
Wallet: Extension 
Speed: https://www.speedtest.net/result/15996871697
NFT: DATANFTFT-e0b917-02

Data-dex:

1. 4.03 sec
2. 3.63 sec 
3. 3.57 sec
4. 3.53 sec
5. 3.45 sec

Explorer: 
1. 9.82 sec
2. 9.20 sec
3. 8.54 sec
4. 8.67 sec
5. 8.88 sec
