### ISSUE TITLE
Intro section

### ISSUE THREAD

**Issue by damienen** [Itheum/explorer-dapp#29]
On explorer, the trailblazer app should have a sort of "intro" section that gives you an intro on the TB (as user may not have access to the TB to see the data). Design needed from our UI/UX designer for this one. @fuzzyduke your social skills are needed 🥇

**Comment by fuzzyduke** [comment]
Our designer is on this @damienen 
Should be ready by Wednesday 5/7/2023.

**Comment by fuzzyduke** [comment]
Hi @damienen @icegriffinguru Kindly find attached the requested banner for the TB App Page.

![Frame 1376156843 (3)](https://github.com/Itheum/explorer-dapp/assets/121969933/e4514e24-58eb-4933-8eec-1746c9e1c0ba)

**Comment by damienen** [comment]
Solved. Closing.
