### ISSUE TITLE
Error seen while Launch time capsule data NFT on explorer.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/explorer-dapp#297]
Launch time capsule data NFT on explorer. Below error is seen

![image](https://github.com/Itheum/explorer-dapp/assets/121969933/4f0a8446-80b7-4706-9f19-bbbbf385c8b2)

**Comment by damienen** [comment]
I was not able to reproduce using extension @fuzzyduke

**Comment by damienen** [comment]
Moving to 1.13.0 so we don't forget to keep this in check, but it seems non reproducable

**Comment by damienen** [comment]
We could do better error handling here

**Comment by newbreedofgeek** [comment]
until we can repro... we should close it
