### ISSUE TITLE
NF-Tunes FE improvement to get it faster

### ISSUE THREAD

**Issue by damienen** [Itheum/explorer-dapp#304]
FE Improvement: don't wait for the first request to finish, request the song with id 1, as it always will be available.
should result in ~5-6 seconds loading time until sound is heard

**Comment by 911-Benedek-RobertGeorge** [comment]
to check:
-the time improvement until you can hear the song
-be sure the first song loaded is the one from that data nft
-check that the song is not reloading after a few seconds

my medium time is : 7-8 sec now

**Comment by damienen** [comment]
Can confirm. Works for me as well.

Time on test: ~11 sec
Time on preview linK: ~8 sec
