### ISSUE TITLE
Web Wallet fix breaks TB App and possible other apps as well.

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/explorer-dapp#33]
When trying to use the data marshal, it's now broken

<img width="1110" alt="image" src="https://github.com/Itheum/explorer-dapp/assets/743169/fcf44dd4-7c1d-496b-b8e6-2b94ca70352d">

**Comment by icegriffinguru** [comment]
Fixed

**Comment by damienen** [comment]
Solved. Closing.
