### ISSUE TITLE
Bitz Play Countdown in Header and Game Launch Screen

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/explorer-dapp#345]
Can you work on this update to BitZ today when you start work:

https://www.loom.com/share/9c6c72d340244041af5e9913d9ffbd91

2 Tasks:
- Show Countdown to next Claim / Claim your BitZ in header
- Show Countdown when user clicks on "Play".  Even with Countdown, ask the user if they want to "Burn A Meme Anyway" or "Come Back Soon"

Let me know if you have any questions

**Comment by fuzzyduke** [comment]
Verified
