### ISSUE TITLE
show a "glowing" - ping dot animation in the bitz header icon for data dex and explorer

### ISSUE THREAD

**Issue by 911-Benedek-RobertGeorge** [Itheum/explorer-dapp#359]
If the cooldown period shows that you can "collect bitz", then show a "glowing" icon in the header for data dex an explorer. Something like this
add a hover tooltip - "you can play bitz"

![Image](https://github.com/Itheum/explorer-dapp/assets/72063093/b4938d16-a9c9-48a7-bb1a-282b885b4989)

**Comment by fuzzyduke** [comment]
This item can be close pending a clarification.

There seems to be a load time before the points are loaded, the bubbles appear even when the points are not loaded yet. This results in bubble been shown even for a brief period even though the user is on a cooldown.

@damienen @newbreedofgeek

**Comment by fuzzyduke** [comment]
Closing.

**Comment by fuzzyduke** [comment]
Posting comment from developer.

1. this one should be solved
2. can't really be solved without a lot of overhead and that's fine.

**Comment by fuzzyduke** [comment]
1. looks fine. 

closing
