### ISSUE TITLE
UX Improvements for Bubbles App

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/explorer-dapp#37]
Hi @icegriffinguru 

Pls fix 3 things as per here : https://www.loom.com/share/6560a68c98174f14b0ab85d42857795f

CC @damienen

**Comment by icegriffinguru** [comment]
- Change color of scroll bar
- Allow zooming only when the user clicks the map
- Drag functionality

First one is done.
Second is done by adding "Focus" button. I made clicking the bubble chart to enable/disable scrolling but draggin didn't work with it.
Third, dragging behavior is set by zoom plugin and there is no other option. We need other plugin or other bubble chart library for it but I have not found any alternative yet.

**Comment by icegriffinguru** [comment]
- Change Scrollbar Color

**Comment by fuzzyduke** [comment]
Observations to be clarified.

1. User has to click on focus to be able to zoom, is this assumed to be intuitive for zoom? If this is the selected path for UX maybe change word from focus?
2. User has to select on focus again to be able to scroll down to next section.

Would a button/sticky at the top to move to the next section be more intuitive/user-friendly?

May require internal team test to provide relevant feedback. Please advise @damienen @newbreedofgeek

**Comment by fuzzyduke** [comment]
Drag functionality not observed as this is a limitation.

**Comment by damienen** [comment]
Done. Closing.
