### ISSUE TITLE
PH Support: AppsConfig for Data Widgets should support Data NFT-PH collections

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/explorer-dapp#372]
In data widgets like NF-Tunes, we support Data NFT (SFTs) in this format in `appsConfig.tsx`:
<img width="585" alt="image" src="https://github.com/Itheum/explorer-dapp/assets/743169/d5b49d3d-2e13-4b7e-a932-adc67481b8ec">

But, with Data NFT-PH collections, they wont be SFTs. We need the ability to add Data NFT-PH collection like this : https://devnet-explorer.multiversx.com/collections/OASMUSICPL-47b186/roles

we have to upgrade `appsConfig.tsx` to also show Data NFT-PH collections for data widgets.

**Comment by damienen** [comment]
Substeps needed on order to solve this:
- save all nfts a person owns inside store
- have all NFT related showings be based on that store variable
- add pagination on all widgets + wallet

**Comment by damienen** [comment]
When checking this issue look out for this:
1. No loading time for NFTs when loading explorer. 
2. No bugs like "no nfts owned" in wallet and widgets
3. Have NFT pagination in wallet and widgets

**Comment by fuzzyduke** [comment]
1. Passed
2. Fail - please check below.
3. Pass

tested on [pr ](https://deploy-preview-397--dulcet-cat-1cfbfd.netlify.app/my-wallet)

![Image](https://github.com/Itheum/explorer-dapp/assets/121969933/3312561b-8014-42f4-b661-ad4f6dccc8df)

**Comment by fuzzyduke** [comment]
Verified. Passed
