### ISSUE TITLE
When File Viewer has a issue reading file content, it should show a "error message" to the user

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/explorer-dapp#38]
I tried to view this Data NFT using file viewer on the explorer wallet section:

<img width="1339" alt="image" src="https://github.com/Itheum/explorer-dapp/assets/743169/b47268ea-651a-4fdc-bc71-001286050ccf">

This is most likely a file that is not JSON or our other support types (image, mp3) etc and therefore it failed.

If it's not a supported file type, then we need to show the following error message to the user.

"Sorry, this file type is currently not supported by the Explorer File Viewer. The file type is [show mime-type from header]"

**Comment by vmradulescu** [comment]
Fix verified.
