### ISSUE TITLE
Bitz Bounties : Issues to be Fixed

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/explorer-dapp#400]
4 issues noticed.

All shown here: https://www.loom.com/share/4b237fbdab7d432ab6bb42aca515d6d2

1. When you power up , the bounty balance is not updating correctly. You have to reload page for it
2. Align leaderboard panel
3. After a power-up, next to the tweet button, back have a smaller button to <back> that closes the tweet panel and goes back to the give bits panel
4. After the give bits is a a success, can we do confetti as well

**Comment by fuzzyduke** [comment]
1. Opacity in light mode needs to be reviewed.

![image](https://github.com/Itheum/explorer-dapp/assets/121969933/782b6322-16b3-4ed8-b86f-955a6165cd26)

2. Upon sending BiTz loading state seen, does not conclude and update with points

![image](https://github.com/Itheum/explorer-dapp/assets/121969933/160da8ef-6eeb-43aa-8a69-7df5b1181808)

3. Users can open up all leaderboards across various bounties concurrently, Suggest that only 1 be open at 1 time.

![image](https://github.com/Itheum/explorer-dapp/assets/121969933/541cb531-bc1a-41b6-bd85-f6af6d872560)

4. When moving the bar for some reason cannot select some numbers like 3,9

![image](https://github.com/Itheum/explorer-dapp/assets/121969933/3ffc4a12-40b7-4586-ad57-a118cd4e3c61)

**Comment by fuzzyduke** [comment]
5. Should we have a state if the user has no points to give? Currently the bar is just disabled, but the user can check the terms box.

![image](https://github.com/Itheum/explorer-dapp/assets/121969933/730425c2-0b64-4c95-92be-b591a2454ec2)

**Comment by damienen** [comment]
1. Remove address from the share links
2. Submitted id -> instead of copy address send to MvX explorer

**Comment by damienen** [comment]
Recommended (if have time):
1. when hovering the buttons "Send x BiTz" or "X Tweet" doesn't give the feeling that something is happening, can we add something like changing the background color to give the feeling that an interaction is happening?
2. Leaderboard button - same hovering issue

**Comment by 911-Benedek-RobertGeorge** [comment]
Unsolved: edsel - 3,4,5 
ovidiu from the second list -  3 , and have to take a better look at 2 


this part might take a little to load, not sure what is the issue here, need to search more 

![Image](https://github.com/Itheum/explorer-dapp/assets/72063093/472f3fde-18b6-48fc-85ca-17ddff095ec3)

**Comment by 911-Benedek-RobertGeorge** [comment]
STG testing ... 
Cant click on fill this bounty... when leaderboard is closed 
Bogdan: Also, "Fill this Data bounty as a Data NFT" - the CTA for creators is missing the word Data - should we add "data" ? 
given bitz will update before the sending process being ready, the input slider will jump right after. -- make all the updates from one go

Here should be added from alignment from start? 
![Image](https://github.com/Itheum/explorer-dapp/assets/72063093/dd5a11cb-9d95-4d55-92b0-c4d17d77b6a5)
