### ISSUE TITLE
All Addresses on Bits Page should be clickable to open in new tab and look the same

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/explorer-dapp#413]
All addresses, in all leaderboards and text etc should be clickable and open in new tab...

For e.g. 
<img width="739" alt="image" src="https://github.com/Itheum/explorer-dapp/assets/743169/9cd04058-08c9-46b2-8bfa-be2b8cbaa906">
(But pls do this for ALL addresses on the page not just the items show above in image)

**Comment by fuzzyduke** [comment]
Tested on test.explorer and pr 412. Leaderboard addresses not clickable.

![Image](https://github.com/Itheum/explorer-dapp/assets/121969933/06e55b81-7f37-4d1c-9fc3-9e013bfc5c9a)

**Comment by fuzzyduke** [comment]
Verified. Fixed.
