### ISSUE TITLE
Explorer - redesign

### ISSUE THREAD

**Issue by damienen** [Itheum/explorer-dapp#42]

**Comment by newbreedofgeek** [comment]
As discussed;
- Get UI/UX for key screen done by Harbsy
- @Enciusan to work out time effort and complexity to migrate to Tailwind
- Redesign the app

**Comment by newbreedofgeek** [comment]
Let's move this to 1.5 as we have some bugs to fix to stabilise 1.4 before we can do this

**Comment by vmradulescu** [comment]
Mobile view does not have dark/light toggle mode button @Enciusan

**Comment by vmradulescu** [comment]
Fix verified. Closed.
