### ISSUE TITLE
add a sum badge into each bounty card

### ISSUE THREAD

**Issue by 911-Benedek-RobertGeorge** [Itheum/explorer-dapp#422]
each bounty card should have a total sum and nr of participants

**Comment by 911-Benedek-RobertGeorge** [comment]
the bounties are sorted by the sum descending

The sum is not updating when the user gives some more bitz, for this i have to ask

**Comment by damienen** [comment]
Ideally the badge gets updated whenever someone sends Bitz as well. If that is too complicated to do in this sprint we can create an issue in Future Work for it when we close this issue

**Comment by fuzzyduke** [comment]
will conclude test once pushed to test.datadex

**Comment by 911-Benedek-RobertGeorge** [comment]
badges updating on power up solved

**Comment by fuzzyduke** [comment]
Verified. Fixed
