### ISSUE TITLE
Move NFTs display section in NF-Tunes to the top of the page

### ISSUE THREAD

**Issue by damienen** [Itheum/explorer-dapp#443]
With more music Data NFTs to be added in NF-Tunes, it is hard for someone to listen to the music. Can we add the Data NFTs on top and then sharing all the benefits etc?

Currently, the available Data NFTs are on the bottom of the section

 - @BogdanCostinas

**Comment by fuzzyduke** [comment]
Verified. Fixed.

Seen in second block

![image](https://github.com/Itheum/explorer-dapp/assets/121969933/98bd90e7-e44a-404e-bb32-e5380b6e40f2)
