### ISSUE TITLE
Explorer : Open TrailBlazer App "web links" an internal embedded "Web View"

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/explorer-dapp#52]
- Users can open TrailBlazer NFTs via the custom built app on Explorer : https://explorer.itheum.io/project-trailblazer
- The app takes a raw JSON file and visualizes it. Web Links are used as actions for the user. Here are some examples

Join Quest Button is a web link
![Image](https://user-images.githubusercontent.com/743169/255876743-1f0ee540-5669-4a7f-aa76-f9a922bd075a.png)

See more link is a web link
![Image](https://user-images.githubusercontent.com/743169/255876834-2ee91862-5b55-469e-98b0-aab4e1acc2d0.png)

At the moment, we are just open this web link in a new browser tab. There is not a good UX as the user exits the app. It's worse on mobile as the user loses all context.

Before you start:
- Most likely the only way to build this feature / "Web View" is by using iframes. iFrames have a lot of restrictions, we need to 1st work out if it's even possible to do this. As most Web Links initially will be a Google Form, try a rough prototype to load a Google Form inside a Web View in the TrailBlazer App. This way we can 1st check feasibility before a full implementation.

Full Implementation:
- When the user clicks on a web link within the TrailBlazer app, open a new model that is a form of "Web View". 
- It shows a "loading"... and then loads in the URL of the target web link
- The original web link should NOT be visible in the UI to the user (they should only see the loaded web page)
- The "header panel" of this "Web View" should have a "Close" option. When a user clicks on this, it should go back to this below view and be in the same scroll position so the user knows which Link / Button they clicked

![Image](https://user-images.githubusercontent.com/743169/255877670-79ac8e0b-5506-4d9d-aa6c-a6edef1f6140.png)

- Needs to work on Mobile, Tablet and Desktop
- Needs to have support for Light and Dark Mode

Stretch Goals:
- If it's possible and you have time, "header panel" of this "Web View"  should have a Next and Previous button as well. And clicking on this will move to Next or Previous Web Link and load it. This was the user can scroll through all web links in the TrailBlazer just within the Web View

**Comment by fuzzyduke** [comment]
While opening in mobile it is seen that instead of opening within the embedded view, it opens in a new page. 

Device: Vivo Y15s

@Enciusan

**Comment by damienen** [comment]
Double press issue solved. The other issue can't happen in prod so pushing for now
