### ISSUE TITLE
Rename Browser Wallet to DeFi Wallet

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/explorer-dapp#53]
As per title,

![Image](https://user-images.githubusercontent.com/743169/255913330-24ca9213-f9d1-4a4d-a423-bbb9e80b2111.png)

**Comment by newbreedofgeek** [comment]
@911-Benedek-RobertGeorge this can be your intro to the MultiversX ecosystem. We have an app called "Explorer" and this isa. simple item to fix

**Comment by fuzzyduke** [comment]
Verified. Fixed. 

Shows as "Defi Wallet"

![image](https://github.com/Itheum/explorer-dapp/assets/121969933/2bf4291f-9573-4326-a8df-130685f4bfda)
