### ISSUE TITLE
"Connect wallet" preferred over "Login" for some users.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/explorer-dapp#54]
Users are reporting that they were looking for terminology like "Connect Wallet" instead of Login. 

Item to be reviewed for implementation.

![image](https://github.com/Itheum/explorer-dapp/assets/121969933/dc577fee-dee7-44bf-9350-c5634e87fdf0)

**Comment by newbreedofgeek** [comment]
duplicate
