### ISSUE TITLE
Login button be shown as an actual button in navbar

### ISSUE THREAD

**Issue by damienen** [Itheum/explorer-dapp#55]

**Comment by newbreedofgeek** [comment]
Make the Login look like a button, similar to 
<img width="116" alt="image" src="https://github.com/Itheum/explorer-dapp/assets/743169/45e4f3f6-001b-4c39-937f-72de76e2ba5a">

**Comment by icegriffinguru** [comment]
Fixed

**Comment by damienen** [comment]
Works. Closing
