### ISSUE TITLE
Tweaks to TB View

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/explorer-dapp#57]
Minor tweaks requested on the TB view rendered by the Itheum Explorer

1. Instead of having the window title as "Itheum Trailblazer" change it to just "Trailblazer"
2. Currently the time on each component shows as 00:00:00 GMT, so kindly remove this component.

![image](https://github.com/Itheum/explorer-dapp/assets/121969933/0472763b-a017-4b2e-8bc1-0aa47436065a)

**Comment by newbreedofgeek** [comment]
Instead of having the window title as "Itheum Trailblazer" change it to just "Trailblazer" - FIXED

Currently the time on each component shows as 00:00:00 GMT, so kindly remove this component. - STILL OPEN

**Comment by damienen** [comment]
Solved. Moving to review

**Comment by fuzzyduke** [comment]
Verified. Fixed.

Both items verified on #108 

![image](https://github.com/Itheum/explorer-dapp/assets/121969933/094b5110-50d2-4532-8a23-2a42e6a1d101)
