### ISSUE TITLE
Switch to the right imports of message signing method

### ISSUE THREAD

**Issue by damienen** [Itheum/explorer-dapp#61]

**Comment by icegriffinguru** [comment]
@damienen , can you share more details?

**Comment by damienen** [comment]
The right way to import useSignMessage:
https://github.com/multiversx/mx-template-dapp/blob/main/src/pages/SignMessage/SignMessage.tsx

The way we do not want to import anymore:
https://github.com/Itheum/explorer-dapp/blob/2c67157b959532fc960b0eaa0c4fd3a30dac36d5/src/pages/EsdtBubble.tsx#L4

**Comment by icegriffinguru** [comment]
Updated

**Comment by newbreedofgeek** [comment]
Fixed
