### ISSUE TITLE
Wallet View should show "total supply" AND "balance"

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/explorer-dapp#63]
Currently in the Wallet, a tile looks like this:
<img width="410" alt="image" src="https://github.com/Itheum/explorer-dapp/assets/743169/b5851e53-2a2a-4552-80bf-cb5d5cc941f1">

This same Data NFT on the Data DEX wallet looks like this:
<img width="293" alt="image" src="https://github.com/Itheum/explorer-dapp/assets/743169/9851fd21-cf1a-4add-92a2-06f431f6a8be">

Updates Needed:
- Like in the Data DEX, on Explorer's tile show both these.
```
Balance: 1
Total supply: 25
```

**Comment by icegriffinguru** [comment]
I've added "balance" attribute to the sdk.

**Comment by icegriffinguru** [comment]
Updated

**Comment by newbreedofgeek** [comment]
@vmradulescu to review and close if fixed

**Comment by damienen** [comment]
Information is there, but the text should be aligned with the rest of the text

![Image](https://github.com/Itheum/explorer-dapp/assets/44813558/c4d26eb3-c4f3-4cc3-81aa-282894e10c4d)

**Comment by icegriffinguru** [comment]
Fixed alignment.

**Comment by damienen** [comment]
Works. Closing
