### ISSUE TITLE
My listed offers UI broken, first row tiles are of different size from the second row.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/explorer-dapp#67]
My listed offers UI broken, first row tiles are of different size from the second row.

![image](https://github.com/Itheum/explorer-dapp/assets/121969933/05b5f2f1-7d9a-4e83-a828-05e616609c69)

**Comment by newbreedofgeek** [comment]
Need to try and rep-pro and fix if an issue.

**Comment by vmradulescu** [comment]
Fix failed when attempting to list more than 6 individual NFT's.

The screen goes blank when trying to go to my listed offers. This is repro'd on 3 different browsers and on mobile.

For a split second, this is how the screen looks:



![Image](https://github.com/Itheum/explorer-dapp/assets/141028717/45bfe5d6-3a34-4a7b-ab1b-f08679ad0b62)

Afterwards, it looks like this:



![Image](https://github.com/Itheum/explorer-dapp/assets/141028717/b4f449b5-881f-4fe7-9a5e-5086c4af243b)

**Comment by vmradulescu** [comment]
Fix verified. Closed.
