### ISSUE TITLE
Request to categorize quiz and quest seperately, currently it is under the same categorization in the TB App.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/explorer-dapp#68]
Request to categorize quest and quiz separately. 

If the category is seen as Quiz 

If the category is seen as Quiz, then please have the component similar to that of quest but with the following Changes
1. Instead of "Psst! A secret quest is underway" have "Psst! A secret quiz is underway"
2. Change from "Open Dialog" to "Join Quiz"

-BC

![image](https://github.com/Itheum/explorer-dapp/assets/121969933/99d90f45-6e50-4d47-bb3b-d5186a9d60a5)

**Comment by newbreedofgeek** [comment]
@vmradulescu pls add this to the new TB view updates
