### ISSUE TITLE
Supply showing 0 in Explorer App View

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/explorer-dapp#69]
In App View on Explorer, when the Data NFT tile loads it shows 0 as the "Supply"

<img width="1372" alt="image" src="https://github.com/Itheum/explorer-dapp/assets/743169/c6e691dc-b634-4451-a58c-4a93d2408a93">

**Comment by icegriffinguru** [comment]
It was an sdk issue. (createManyFromApi).
I fixed the issue and pushed the update.

**Comment by icegriffinguru** [comment]
Fixed

**Comment by damienen** [comment]
Solved
