### ISSUE TITLE
File Viewer to support inline rendering of images

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/explorer-dapp#7]
- When you got go to `My Wallet` and click on "View Data" for any Data NFTs that returns JSON, we can see this "File Viewer" show the JSON data inline.

<img width="1205" alt="image" src="https://github.com/Itheum/explorer-dapp/assets/743169/1ca53706-f4eb-4ad0-bb55-9414a0ef702b">

## Add support for Images ##
- We need to extend the File Viewer to also show images inline. Images can be in PNG, JPG, GIF, SVG etc. 
- Buy this Data NFT (it might be SVG or PNG not sure) : https://stg.datadex.itheum.io/datanfts/marketplace/DATANFTFT4-3ba099-01a0/offer-1963
- At the moment, when we try and view the content - I think the Data NFT SDK or app breaks with a JSON parse error (as the content is not JSON)
![image](https://github.com/Itheum/explorer-dapp/assets/743169/801ac2c0-2263-4847-a45e-b9b17d0cba89)

### What should happen: ###
- The image should render inside the "File Viewer" body section of the model.
- It should be resized nicely if it's a large image with a scroll bar to see the entire image.  Zoom feature will be nice to have.
- You can use some image view plugins if needed (not needed if you can do it natively your self) - e.g. https://turbofuture.com/graphic-design-video/React-Image-Viewer or you can find a better one

**Comment by icegriffinguru** [comment]
@newbreedofgeek 
SDK's viewData method converts response to JSON in default, `const data = await response.json();`
We need to check response type in SDK or return url to frontend for further check.

**Comment by bucurdavid** [comment]
https://github.com/Itheum/sdk-mx-data-nft/pull/10

**Comment by damienen** [comment]
@newbreedofgeek please publish the sdk
