### ISSUE TITLE
Explorer Wallet "File Viewer" needs to detect SVG and render it as SVG (so it can be interactive )

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/explorer-dapp#70]
- Here is the video explaining issue - https://www.loom.com/share/9be7b678ba8c4b70b7056e3f39b31547
- Upcoming Bubble Map SVG has some "interactions" in it
- But when we render it in Explorer File View - the SVG is rendered as an image with no interactions.

What we need:
- Can you please have a look if you can make the interactions appear in Explorer?
- Here is the Data NFT with the SVG - https://stg.datadex.itheum.io/datanfts/marketplace/DATANFTFT4-3ba099-01a0 
- 
![image](https://github.com/Itheum/explorer-dapp/assets/743169/97d289c4-e3de-407b-a6db-d9163bd650c4)

**Comment by damienen** [comment]
Solved
