### ISSUE TITLE
Listed value in "my-listed" is still broken 

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/explorer-dapp#76]
Data DEX is correct:
<img width="304" alt="image" src="https://github.com/Itheum/explorer-dapp/assets/743169/ca9b39ec-8f34-4b99-a57f-83a143b330fc">

Data Explorer "my-listed" is wrong:
<img width="366" alt="image" src="https://github.com/Itheum/explorer-dapp/assets/743169/b7abefe7-ff1d-4a67-a43a-8139110636b5">
Why is Listed showing 89??

**Comment by icegriffinguru** [comment]
@newbreedofgeek , I've examined code but it looks fine except it did not check the user is logged.
I've update the code and plz check again.

**Comment by newbreedofgeek** [comment]
not working
