### ISSUE TITLE
View Data on items in Wallet doesnt properly render Data NFT content + Web Wallet does not work in Explorer Wallet

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/explorer-dapp#78]
Description: 
Data NFTs in the wallet do not render correctly.

When clicking on "View Data" on Data NFTs in the wallet:
1. The Trailblazer should show in json format. It currently shows the same render as in the Trailblazer app.
2. Web wallet is not supported when viewing Non Trailblazer Data NFTs.

![image](https://github.com/Itheum/explorer-dapp/assets/121969933/7973abdf-d28d-4f90-b175-e02c3b1804ed)

**Comment by newbreedofgeek** [comment]
@icegriffinguru 

This is for you.

In the Explorer Wallet, when user's click on "Web Data" it needs to show the "raw data" in the "File Viewer" (JSON, PNG, etc).

The behaviour above is wrong, for TrailBlazer Data NFT it's showing the UI (this should ONLY be viewable in the Trailblaer App), not the wallet.

As part of this Ticket, also add "Web Wallet" support for VIew Data in the Explorer Wallet

**Comment by icegriffinguru** [comment]
Fixed

**Comment by damienen** [comment]
Solved in 1.3.0, will merge to 1.4.0. Closing.
