### ISSUE TITLE
Create New App called "ESDT Bubbles"

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/explorer-dapp#8]
- We have a new Data NFT from a community member that shows all the wEGLD holders in bubble view, you can buy this from here: https://stg.datadex.itheum.io/datanfts/marketplace/DATANFTFT4-3ba099-01a1/offer-1964
- In the Explore create a new app based called "ESDT Bubbles".
- Visualise the data in a bubble view when the user clicks on "View Data". To get an idea of what the final bubble chart should look like you can buy this Data NFT (which has a static bubble chart of the same data) : https://stg.datadex.itheum.io/datanfts/marketplace/DATANFTFT4-3ba099-01a0/offer-1963

If you have more questions about what the bubble chart should look like, please check with @BogdanCostinas and @fuzzyduke 

Tasks
- [x] (1) Change the BG of this table (just remove the green bg for lite mode) For dark mode, remove the green bg and also make font color white and link color like below.

- [x] (2) Can you show all top 250 in the table as well? (full dataset)..
If it's too long... maybe a simple client side paging..
Show 50
Button called [Show More]
Show next 50

- [x] (3) Can these bubbles be a new link to explorer, like you have done in the table?

- [x] (4) Does this support "zoom"? Where you can zoom in and drag etc? (for Bubble chart)

- [x] (5)  Is there any easy way to know if an address is a SC or user address and show an icon?

**Comment by icegriffinguru** [comment]
Regarding (5) Is there any easy way to know if an address is a SC or user address and show an icon,
we need data with address info. (because calling MVX API 250 times to get account info on FE is not a solution)

**Comment by damienen** [comment]
Can't you just check if an address starts with erd1qqqqq and is yes it's an SC?

**Comment by icegriffinguru** [comment]
Yes
thanks, @damienen 
Fixed (5)

**Comment by fuzzyduke** [comment]
1. When trying to select an area on the visual an odd zoom effect is seen and the user has to scroll all the way up to reset zoom. Also the intended action was to drag but it selected an area instead.
![image](https://github.com/Itheum/explorer-dapp/assets/121969933/46ef4102-06c2-40a7-967a-e658b99c3cb1)
2. While in the view pane is it possible to keep the Reset Zoom in 1 place? When we get to the table section the button does not have to be there. Reason is because if you zoom in the mid, you need 2 action to reset zoom, which is to scroll up and then click reset.

**Comment by fuzzyduke** [comment]
Also consider keeping the legend viewable as the user has to scroll to the bottom of the visual to see the legend. Minor suggestion.

**Comment by icegriffinguru** [comment]
1) is normal behavior of zoom plugin. I used zoom plugin and its drag behavior is not changable.
2) reset button has sticky behavior now
3) add another legend at the top

**Comment by damienen** [comment]
Closing for now. Seems good
