### ISSUE TITLE
if you click anywhere outside Models, then the model closes

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/explorer-dapp#83]
Suggestion if is possible:
At the current stage, if you click anywhere outside the circled area, the page will close and you will need to sign the message again. Can you make it impossible to click outside this area and if you want to Close the page to be mandatory to press the "X" ?

![image](https://github.com/Itheum/explorer-dapp/assets/743169/305391af-3733-4911-9f80-765f5f166bb8)

**Comment by fuzzyduke** [comment]
While scrolling down there is no close button. The user has to scroll back up. 

![image](https://github.com/Itheum/explorer-dapp/assets/121969933/234c87d7-9ad5-4239-822d-0e8537d99e90)

**Comment by newbreedofgeek** [comment]
that's normal UX and dont' think it's need to have more close buttons. If requested by users, we can add one
