### ISSUE TITLE
Wallet view's "View Data" does NOT support Web Wallet - so need to show a good message to user

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/explorer-dapp#85]
so show error message to user so it's clear what to do next

![image](https://github.com/Itheum/explorer-dapp/assets/743169/5f894688-1047-4494-b549-d95affa90659)

**Comment by fuzzyduke** [comment]
Verified. Seen on Explorer.

![image](https://github.com/Itheum/explorer-dapp/assets/121969933/8630495f-523b-4299-97d0-222e61f32f4b)
