### ISSUE TITLE
Dark / Light Mode on header needs to follow the Data DEX Style

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/explorer-dapp#88]
Currently, Explorer mode switched looks like this:
<img width="90" alt="image" src="https://github.com/Itheum/explorer-dapp/assets/743169/3819da3c-96d8-4f76-a95e-6de44cc28ce6">

Expected:
1. Needs to follow Data DEX style:
<img width="72" alt="image" src="https://github.com/Itheum/explorer-dapp/assets/743169/1c8dbfc9-0574-4290-b916-9b36b69049d8">

2. Should default to "dark" mode for new users
3. Should "remember" dark vs light mode on browser refresh and icon should also match

**Comment by damienen** [comment]
The only thing here would be to make the icon similar (if possible the same) as for Data Dex

**Comment by 911-Benedek-RobertGeorge** [comment]
@Enciusan did the dark-light-system mode on the explorer, and I did it on Data-dex, it looks like this


![Image](https://github.com/Itheum/explorer-dapp/assets/72063093/063f9918-1c79-42f1-9890-ab191de386a6)

**Comment by vmradulescu** [comment]
Checked. Works as intended. Fixed.
