### ISSUE TITLE
Add zoom capability for bubbles

### ISSUE THREAD

**Issue by damienen** [Itheum/explorer-dapp#89]
References:
https://www.npmjs.com/package/react-svg-pan-zoom
https://blog.logrocket.com/using-dangerouslysetinnerhtml-in-a-react-application/
https://npm.io/package/dompurify

**Comment by newbreedofgeek** [comment]
Hi @icegriffinguru 

I'll give this to you.

- this is the SVG app for MultiversX Bubbles - https://stg.explorer.itheum.io/multiversx-bubbles
- You built the SVG viewer for this and I made some updates to it to make links open in new window.
- We now want to try and implement a "pan and zoom" feature like you see here : https://www.npmjs.com/package/react-svg-pan-zoom
- This pan and zoom feature should ONLY be in the multiversx-bubbles app and NOT on other SVG file viewer (my wallet)


Have a look and ask me any questions.

**Comment by icegriffinguru** [comment]
Mobile-friendly.

**Comment by vmradulescu** [comment]
https://www.loom.com/share/1c6db298a9b344f3aedc1d0e3e5364c1?sid=e26ff09c-22f7-4d9a-a3fb-c65810a71b86

@icegriffinguru 

Above my feedback for the implementation on desktop. Thanks @Enciusan for the tips as well.

**Comment by newbreedofgeek** [comment]
@icegriffinguru I agree with @vmradulescu 's recommendations above.

In Summary, let's do the following>


1. Contain the "Image to the height of the visible Model". Centre it (margin: auto). Maintain aspect ratio

![image](https://github.com/Itheum/explorer-dapp/assets/743169/97b0d7bf-0754-490a-8fa7-bc68887a9cf5)

See example in image.. i.e. 

```
    width: auto;
    aspect-ratio: 1 / 1;
    height: 475px; // you may need a way to dynamically detect and set this based on actual screen (desktop, mobile etc)
    margin: auto;
```

2. Make Icons bigger and make move them more towards the inside so it's more visible. Also, remove the scroll bar from the model body so user does not try and scroll and ONLY used the pan and zoom tools.

<img width="1256" alt="image" src="https://github.com/Itheum/explorer-dapp/assets/743169/f899a50d-330a-4c24-98e2-7db544660e8b">


3. Test on Desktop, Tablet and Mobile view to make sure UX works the same for all.

**Comment by newbreedofgeek** [comment]
Only issue I just saw, is that we may end up with this when we do the above and do "pan and zoom"

<img width="1371" alt="image" src="https://github.com/Itheum/explorer-dapp/assets/743169/2c3391e5-442a-4bcc-9854-80212de56972">

Need to think of a better UX... give me some time

**Comment by newbreedofgeek** [comment]
I think this solves it:
https://www.loom.com/share/ee46c55f7c244fcbacc67f20b20d3356

1. Set some intial zoom level and zoom into the "centre of image". This way the image takes the full canvas.
2. Make the icons bigger so the user sees them and knows that they need to interact with the image via the icons
3. Maybe hide the overflow on the body? so that the scroll bar is not used

See video above.

@icegriffinguru @vmradulescu

**Comment by vmradulescu** [comment]
When initially opening the bubble map, it does not fit the screen, its around 60-70% of the bubble map. Reproduceable both on desktop and mobile. When clicking the fit to screen button, it is the same behaviour.

![image](https://github.com/Itheum/explorer-dapp/assets/141028717/47ea6753-c9a6-41c0-9d76-e7c2349d9612)


Expected: When opening the bubble map, it should completely fit the screen. Same with clicking the fit to screen button.

![image](https://github.com/Itheum/explorer-dapp/assets/141028717/abdd3f41-dc0a-473b-88cd-10f64e5a1ea7)
