### ISSUE TITLE
SDK returns error in Explorer

### ISSUE THREAD

**Issue by damienen** [Itheum/explorer-dapp#93]
Steps to reproduce:
1. Make sure you have EXACTLY 1 listing on the marketplace
2. Go to https://stg.datadex.itheum.io/datanfts/marketplace/DATANFTFT4-3ba099-3e and buy 89 pieces (devnet)
3. List those 89 for 10 ITHEUM (10.2 with tax)
4. Go to stg explorer and go to my listed

![Image](https://github.com/Itheum/explorer-dapp/assets/44813558/7e562556-e1f2-4200-afaf-c15b2db9211c)

**Comment by bucurdavid** [comment]
What is the error?

**Comment by damienen** [comment]
Cannot create data nft from api if I remember well
